インクルメンタルサーチ実装
tetsu-26/chat-space pull request #13
Opened 2019-03-12 12:46 UTC by tetsu-26

# What
Chat-space インクルメンタルサーチ実装

# Why
グループにユーザー登録する際インクルメンタルサーチが必要だから

2019-03-12 12:49 UTC, TOMARUMARU reviewed
gifにて挙動をお見せ下さい

2019-03-12 13:04 UTC, ghost requested changes

2019-03-12 13:04 UTC, hiroki5123 commented on app/assets/javascripts/user.js
> +function appendUser(user) {
インデント一個奥です

2019-03-12 13:04 UTC, hiroki5123 commented on app/assets/javascripts/user.js
> +var search_list = $("#user-search-result");
インデント一個奥です

2019-03-13 02:01 UTC, miyagit commented on app/views/groups/_form.html.haml
> +        %input#user-search-field.chat-group-form__input{:placeholder => "追加したいユーザー名を入力してください", :type => "text"}/
こちらハッシュロケットを直しましょう。

2019-03-13 02:01 UTC, miyagit commented on app/views/groups/_form.html.haml
> +        %input#user-search-field.chat-group-form__input{:placeholder => "追加したいユーザー名を入力してください", :type => "text"}/
こちらハッシュロケットを直しましょう。

2019-03-13 02:04 UTC, hzak2xx approved these changes
LGTM

2019-03-13 02:06 UTC, merged