自動更新実装
tetsu-26/chat-space pull request #14
Opened 2019-03-13 10:55 UTC by tetsu-26

# What
Chat-space自動更新機能実施

# Why
自動更新ができた方が良いから

メッセージ自動更新
https://gyazo.com/c1289006e5dd8f7c254ff8b31783af4c

画像自動更新
https://gyazo.com/b5396f03a31edc03f684871cb99d3dd0

2019-03-13 11:14 UTC, yuki-uchida requested changes

2019-03-13 11:14 UTC, yuki-uchida commented on app/assets/javascripts/message.js
>      function buildHTML(message){
buildHTMLでは、何をどうするのかがわかりづらいので、buildSendMessageHTMLとかいかがでしょうか

2019-03-13 11:14 UTC, yuki-uchida commented on app/assets/javascripts/message.js
> +    function reload(){
なにをreloadするのかわかる名前にしましょう

2019-03-13 11:14 UTC, yuki-uchida commented on app/assets/javascripts/message.js
> +      $.ajax({
message＿idの中でもどんなmessage_idでしょうか？
それがわかる名前だとグッドです

2019-03-13 11:37 UTC, tetsu-26 commented on app/assets/javascripts/message.js
>      function buildHTML(message){
変更しました

2019-03-13 11:37 UTC, tetsu-26 commented on app/assets/javascripts/message.js
> +    function reload(){
変更しました

2019-03-13 11:37 UTC, tetsu-26 commented on app/assets/javascripts/message.js
> +      $.ajax({
変更しました

2019-03-13 11:37 UTC, yuki-uchida commented
pushを忘れていませんか？
また、他の指摘も対応はされましたか？

2019-03-13 11:40 UTC, yuki-uchida commented
file changedを確認してみてください。
指摘後の対応が反映されていません。
コミットアンドプッシュが出来ているか確認してください

2019-03-13 11:45 UTC, yuki-uchida requested changes
ご自分で変更をきちんと確認してください。

2019-03-13 11:45 UTC, yuki-uchida commented on app/assets/javascripts/message.js
> +    function reload(){
変更されていません

2019-03-13 11:56 UTC, tetsu-26 commented
こちらではちゃんと更新されているのですがそちらではされていませんか？
https://gyazo.com/8cf214f0de70aa001db0b60ac72b69b9

2019-03-13 11:59 UTC, TOMARUMARU commented
指摘に関して全ての変更がなされていない、ということですね。

2019-03-13 11:59 UTC, TOMARUMARU commented on app/assets/javascripts/message.js
> +    function reload(){
こちらレビュー受けているので修正しましょう

2019-03-13 12:04 UTC, tetsu-26 commented
指摘後
var new_message_insertという変数をつけて何をしているのかを示しているつもりなのですが、あと何をしてほしいのでしょうか？

2019-03-13 12:06 UTC, TOMARUMARU commented
> なにをreloadするのかわかる名前にしましょう

という指摘に関してです。関数名を変更しましょう、といった意味ですね

2019-03-13 12:13 UTC, tetsu-26 commented
すいません今変数名は変更してみましたがここの変更ではないならどこかわからないので、具体例を提示していただけませんか？

2019-03-13 12:18 UTC, yuki-uchida commented
対応出来ていないようなので近くのメンターにご相談ください。もしくはこちらからご連絡します。いかかですか？

2019-03-13 12:19 UTC, tetsu-26 commented
連絡お願いします

2019-03-13 13:04 UTC, tetsu-26 commented
メッセージを自動更新するという意図でこの変数にしましたがどうでしょうか？

2019-03-14 01:54 UTC, miyagit approved these changes
LGTMです。

2019-03-14 03:08 UTC, merged